In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [2]:
# import the dataset
df=pd.read_csv("HeartDisease.csv")
df.head()

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0   63       1           3       145         233                    1   
1   37       1           2       130         250                    0   
2   41       0           1       130         204                    0   
3   56       1           1       120         236                    0   
4   57       0           0       120         354                    0   

   rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0         0      150            0       2.3      0   0            1       1  
1         1      187            0       3.5      0   0            2       1  
2         0      172            0       1.4      2   0            2       1  
3         1      178            0       0.8      2   0            2       1  
4         1      163            1       0.6      2   0            2       1

In [3]:
df.shape

(303, 14)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   gender               303 non-null    int64  
 2   chest_pain           303 non-null    int64  
 3   rest_bps             303 non-null    int64  
 4   cholestrol           303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   rest_ecg             303 non-null    int64  
 7   thalach              303 non-null    int64  
 8   exer_angina          303 non-null    int64  
 9   old_peak             303 non-null    float64
 10  slope                303 non-null    int64  
 11  ca                   303 non-null    int64  
 12  thalassemia          303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
df.describe().round(1)

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
count  303.0   303.0       303.0     303.0       303.0                303.0   
mean    54.4     0.7         1.0     131.6       246.3                  0.1   
std      9.1     0.5         1.0      17.5        51.8                  0.4   
min     29.0     0.0         0.0      94.0       126.0                  0.0   
25%     47.5     0.0         0.0     120.0       211.0                  0.0   
50%     55.0     1.0         1.0     130.0       240.0                  0.0   
75%     61.0     1.0         2.0     140.0       274.5                  0.0   
max     77.0     1.0         3.0     200.0       564.0                  1.0   

       rest_ecg  thalach  exer_angina  old_peak  slope     ca  thalassemia  \
count     303.0    303.0        303.0     303.0  303.0  303.0        303.0   
mean        0.5    149.6          0.3       1.0    1.4    0.7          2.3   
std         0.5     22.9          0.5       1.2    0.6    1.0          0.6   
min         0.0     71.0          0.0       0.0    0.0    0.0          0.0   
25%         0.0    133.5          0.0       0.0    1.0    0.0          2.0   
50%         1.0    153.0          0.0       0.8    1.0    0.0          2.0   
75%         1.0    166.0          1.0       1.6    2.0    1.0          3.0   
max         2.0    202.0          1.0       6.2    2.0    4.0          3.0   

       target  
count   303.0  
mean      0.5  
std       0.5  
min       0.0  
25%       0.0  
50%       1.0  
75%       1.0  
max       1.0

In [6]:
df.isnull().sum()

age                    0
gender                 0
chest_pain             0
rest_bps               0
cholestrol             0
fasting_blood_sugar    0
rest_ecg               0
thalach                0
exer_angina            0
old_peak               0
slope                  0
ca                     0
thalassemia            0
target                 0
dtype: int64

In [7]:
df.dtypes

age                      int64
gender                   int64
chest_pain               int64
rest_bps                 int64
cholestrol               int64
fasting_blood_sugar      int64
rest_ecg                 int64
thalach                  int64
exer_angina              int64
old_peak               float64
slope                    int64
ca                       int64
thalassemia              int64
target                   int64
dtype: object

In [8]:
for i in df.columns:
    print({i:df[i].unique()})

{'age': array([63, 37, 41, 56, 57, 44, 52, 54, 48, 49, 64, 58, 50, 66, 43, 69, 59,
       42, 61, 40, 71, 51, 65, 53, 46, 45, 39, 47, 62, 34, 35, 29, 55, 60,
       67, 68, 74, 76, 70, 38, 77], dtype=int64)}
{'gender': array([1, 0], dtype=int64)}
{'chest_pain': array([3, 2, 1, 0], dtype=int64)}
{'rest_bps': array([145, 130, 120, 140, 172, 150, 110, 135, 160, 105, 125, 142, 155,
       104, 138, 128, 108, 134, 122, 115, 118, 100, 124,  94, 112, 102,
       152, 101, 132, 148, 178, 129, 180, 136, 126, 106, 156, 170, 146,
       117, 200, 165, 174, 192, 144, 123, 154, 114, 164], dtype=int64)}
{'cholestrol': array([233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 239, 275, 266,
       211, 283, 219, 340, 226, 247, 234, 243, 302, 212, 175, 417, 197,
       198, 177, 273, 213, 304, 232, 269, 360, 308, 245, 208, 264, 321,
       325, 235, 257, 216, 256, 231, 141, 252, 201, 222, 260, 182, 303,
       265, 309, 186, 203, 183, 220, 209, 258, 227, 261, 221, 205, 240,
       318, 298, 564, 277, 2

In [9]:
X=df.values[:,0:-1]

In [10]:
Y=df.values[:,-1]

In [11]:
print(X.shape)
print(Y.shape)

(303, 13)
(303,)


## StandardSCaler

In [12]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

### train_test_split

In [13]:
from sklearn.model_selection import train_test_split

# split the data

X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

### Decision tree-entropy

In [14]:
from sklearn.tree import DecisionTreeClassifier
Model_DT=DecisionTreeClassifier(criterion="entropy",random_state=10)
                                
Model_DT.fit(X_train,Y_train)
Y_pred=Model_DT.predict(X_test) 

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[23 12]
 [ 5 21]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.82      0.66      0.73        35
         1.0       0.64      0.81      0.71        26

    accuracy                           0.72        61
   macro avg       0.73      0.73      0.72        61
weighted avg       0.74      0.72      0.72        61

Accuracy of the model:  0.7213114754098361


## Decision tree -gini

In [16]:
from sklearn.tree import DecisionTreeClassifier
Model_DT=DecisionTreeClassifier(criterion="gini",random_state=10)
                                
Model_DT.fit(X_train,Y_train)
Y_pred=Model_DT.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[24 11]
 [ 5 21]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.69      0.75        35
         1.0       0.66      0.81      0.72        26

    accuracy                           0.74        61
   macro avg       0.74      0.75      0.74        61
weighted avg       0.75      0.74      0.74        61

Accuracy of the model:  0.7377049180327869


In [18]:
Model_DT.score(X_train,Y_train)

1.0

### using cross Validation

In [19]:
from sklearn.model_selection import cross_val_score
CV_model=DecisionTreeClassifier(criterion="gini",random_state=10)
cv=cross_val_score(CV_model,X,Y,cv=10)
cv


array([0.77419355, 0.83870968, 0.87096774, 0.76666667, 0.76666667,
       0.7       , 0.73333333, 0.76666667, 0.7       , 0.76666667])

In [20]:
cv.mean()

0.7683870967741935

### Hypertunning

In [39]:
#Nnumber of tree in random forest 
criterion=["gini", "entropy", "log_loss"]
# number of splitter
splitter=["best", "random"]
#Number of feature to consider at every split
max_features = ['auto', 'sqrt',"log2"]
# Maximum number of levels in tree
max_depth = [2,4,5]
#Minimum number of samples required to split a node
min_samples_split = [1,2]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2,5]



In [40]:
# create the  parameter
parameter={'criterion': criterion,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'splitter': splitter}
print(parameter)

{'criterion': ['gini', 'entropy', 'log_loss'], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [2, 4, 5], 'min_samples_split': [1, 2], 'min_samples_leaf': [1, 2, 5], 'splitter': ['best', 'random']}


In [41]:
from sklearn.model_selection import GridSearchCV
DT=DecisionTreeClassifier()

Grid=GridSearchCV(estimator=DT,param_grid=parameter,cv=10,n_jobs=-1)

Grid.fit(X_train,Y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
        

In [43]:
print (f'Train Accuracy - : {Grid.score(X_train,Y_train):.3f}')
print (f'Test Accuracy - : {Grid.score(X_test,Y_test):.3f}')

Train Accuracy - : 0.822
Test Accuracy - : 0.721


In [42]:
Grid.best_params_

{'criterion': 'entropy',
 'max_depth': 4,
 'max_features': 'sqrt',
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'splitter': 'best'}

In [44]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="entropy",random_state=10,
                                         splitter="best",min_samples_leaf=2, # minmum leaf
                                         min_samples_split=2,
                                         max_depth=4,max_features="sqrt")

#fit the model on the data and predicate the value

model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[29  6]
 [ 4 22]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.88      0.83      0.85        35
         1.0       0.79      0.85      0.81        26

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

Accuracy of the model:  0.8360655737704918


In [45]:
# model_score
model_DecisionTree.score(X_train,Y_train)

0.8057851239669421

## Random_Forest_classifier

In [24]:
from sklearn.ensemble import RandomForestClassifier
RandomForest=RandomForestClassifier(n_estimators=50,random_state=10,criterion="gini")

RandomForest.fit(X_train,Y_train)
Y_pred=RandomForest.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[29  6]
 [ 5 21]]
0.819672131147541
              precision    recall  f1-score   support

         0.0       0.85      0.83      0.84        35
         1.0       0.78      0.81      0.79        26

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



### HyperTunning - GridSearchCV

In [26]:
#Nnumber of tree in random forest 
n_estimators=[int(x) for x in np.linspace(start=10, stop=100,num=20)]
#Number of feature to consider at every split
max_features = ['auto', 'sqrt',"log2"]
# Maximum number of levels in tree
max_depth = [2,4]
#Minimum number of samples required to split a node
min_samples_split = [2,5]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]
# Method of selecting samples for training each tree
bootstrap = [True, False]


In [27]:
# create the  parameter
parameter={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(parameter)

{'n_estimators': [10, 14, 19, 24, 28, 33, 38, 43, 47, 52, 57, 62, 66, 71, 76, 81, 85, 90, 95, 100], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [2, 4], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2], 'bootstrap': [True, False]}


In [28]:
RandomForest=RandomForestClassifier()

In [29]:
from sklearn.model_selection import GridSearchCV
Grid=GridSearchCV(estimator=RandomForest,param_grid=parameter,cv=10,n_jobs=-1)

Grid.fit(X_train,Y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None...
                                              warm_start=False),
             iid='deprecated', n_jobs=-1,
    

In [30]:
Grid.best_params_

{'bootstrap': True,
 'max_depth': 4,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 33}

In [32]:
print (f'Train Accuracy - : {Grid.score(X_train,Y_train):.3f}')
print (f'Test Accuracy - : {Grid.score(X_test,Y_test):.3f}')


Train Accuracy - : 0.926
Test Accuracy - : 0.820


In [34]:
from sklearn.ensemble import RandomForestClassifier
RandomForest=RandomForestClassifier(n_estimators=33,random_state=10,max_depth=4,min_samples_leaf=1,
                                   min_samples_split=2,bootstrap=True,max_features="auto")

RandomForest.fit(X_train,Y_train)
Y_pred=RandomForest.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[27  8]
 [ 4 22]]
0.8032786885245902
              precision    recall  f1-score   support

         0.0       0.87      0.77      0.82        35
         1.0       0.73      0.85      0.79        26

    accuracy                           0.80        61
   macro avg       0.80      0.81      0.80        61
weighted avg       0.81      0.80      0.80        61



### with cross validation

In [36]:
from sklearn.model_selection import cross_val_score
CV_model=RandomForestClassifier(n_estimators=50,random_state=10)
cv=cross_val_score(CV_model,X,Y,cv=5)
cv


array([0.81967213, 0.90163934, 0.78688525, 0.85      , 0.78333333])

In [37]:
cv.mean()

0.8283060109289618

### Extra tree Classifier-- Bagging Process

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier(n_estimators=105,random_state=10)

model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

## Adaboost Classifier- Decision Tree

In [50]:
from sklearn.ensemble import AdaBoostClassifier

Adaboost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion="entropy",
 random_state=10,
 min_samples_leaf=2,
 min_samples_split=2,max_features="sqrt",max_depth=4),
n_estimators=100,
random_state=10)

Adaboost.fit(X_train,Y_train)
Y_pred=Adaboost.predict(X_test)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[26  9]
 [ 4 22]]
0.7868852459016393
              precision    recall  f1-score   support

         0.0       0.87      0.74      0.80        35
         1.0       0.71      0.85      0.77        26

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.80      0.79      0.79        61



## Adaboost Classifier- Random_Forest

In [52]:
from sklearn.ensemble import AdaBoostClassifier

Adaboost=AdaBoostClassifier(base_estimator=RandomForestClassifier(criterion="gini",
 random_state=10,
 min_samples_leaf=5,
 min_samples_split=5,
 max_depth=10),
n_estimators=100,
random_state=10)

Adaboost.fit(X_train,Y_train)
Y_pred=Adaboost.predict(X_test)

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[28  7]
 [ 5 21]]
0.8032786885245902
              precision    recall  f1-score   support

         0.0       0.85      0.80      0.82        35
         1.0       0.75      0.81      0.78        26

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



## Gradient_Boosting

In [54]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import GradientBoostingClassifier

model=GradientBoostingClassifier(n_estimators=100,random_state=10)
#fit the model on the data and predict the values
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[28  7]
 [ 5 21]]
0.8032786885245902
              precision    recall  f1-score   support

         0.0       0.85      0.80      0.82        35
         1.0       0.75      0.81      0.78        26

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



# XGB Boost

In [72]:
from xgboost import XGBClassifier
model=XGBClassifier(n_estimators=70,random_state=10,subsample=0.8, max_leaves=0)
#fit the model on the data and predict the values
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [73]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
# confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[30  5]
 [ 5 21]]
0.8360655737704918
              precision    recall  f1-score   support

         0.0       0.86      0.86      0.86        35
         1.0       0.81      0.81      0.81        26

    accuracy                           0.84        61
   macro avg       0.83      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



# KNN

In [56]:
np.sqrt(len(X_train))

15.556349186104045

In [57]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=15,metric="euclidean")
KNN.fit(X_train,Y_train)

Y_pred=KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[26  9]
 [ 3 23]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.90      0.74      0.81        35
         1.0       0.72      0.88      0.79        26

    accuracy                           0.80        61
   macro avg       0.81      0.81      0.80        61
weighted avg       0.82      0.80      0.80        61

Accuracy of the model:  0.8032786885245902


In [59]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    KNN = KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    KNN.fit(X_train, Y_train) 
    Y_pred = KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.7704918032786885 for K-Value: 1
Accuracy is  0.7540983606557377 for K-Value: 2
Accuracy is  0.8032786885245902 for K-Value: 3
Accuracy is  0.8360655737704918 for K-Value: 4
Accuracy is  0.8524590163934426 for K-Value: 5
Accuracy is  0.819672131147541 for K-Value: 6
Accuracy is  0.8032786885245902 for K-Value: 7
Accuracy is  0.7868852459016393 for K-Value: 8
Accuracy is  0.7868852459016393 for K-Value: 9
Accuracy is  0.819672131147541 for K-Value: 10
Accuracy is  0.7868852459016393 for K-Value: 11
Accuracy is  0.819672131147541 for K-Value: 12
Accuracy is  0.819672131147541 for K-Value: 13
Accuracy is  0.819672131147541 for K-Value: 14
Accuracy is  0.8032786885245902 for K-Value: 15
Accuracy is  0.819672131147541 for K-Value: 16
Accuracy is  0.8032786885245902 for K-Value: 17
Accuracy is  0.8032786885245902 for K-Value: 18
Accuracy is  0.8032786885245902 for K-Value: 19
Accuracy is  0.819672131147541 for K-Value: 20
Accuracy is  0.8032786885245902 for K-Value: 21
Accuracy

In [60]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

5 : 0.8524590163934426


In [61]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
KNN.fit(X_train,Y_train)

Y_pred=KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[28  7]
 [ 2 24]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.93      0.80      0.86        35
         1.0       0.77      0.92      0.84        26

    accuracy                           0.85        61
   macro avg       0.85      0.86      0.85        61
weighted avg       0.87      0.85      0.85        61

Accuracy of the model:  0.8524590163934426


# LogisticRegression 

In [63]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred_log=classifier.predict(X_test)
#print(Y_pred_log)
#print(list(zip(Y_test,Y_pred_log)))

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score, \
classification_report

cfm=confusion_matrix(Y_test,Y_pred_log)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred_log))

acc=accuracy_score(Y_test, Y_pred_log)
print("Accuracy of the model: ",acc)

[[26  9]
 [ 5 21]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.84      0.74      0.79        35
         1.0       0.70      0.81      0.75        26

    accuracy                           0.77        61
   macro avg       0.77      0.78      0.77        61
weighted avg       0.78      0.77      0.77        61

Accuracy of the model:  0.7704918032786885


# SVM

In [65]:
from sklearn import svm

svc_model = svm.SVC(kernel="rbf") # keeping these constant

parameter_space = {
   # 'kernel': ["linear","rbf","poly","sigmoid"],
    'gamma': [0.1,0.01,0.001],
    'C': [1,5,8,10,20]
}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svc_model, parameter_space, n_jobs=-1, cv=5)



In [66]:
clf.fit(X_train,Y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [1, 5, 8, 10, 20], 'gamma': [0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [67]:
print('Best parameters found:\n', clf.best_params_)

Best parameters found:
 {'C': 10, 'gamma': 0.001}


In [68]:
from sklearn.svm import  SVC
svc_model=SVC(kernel="rbf",C=10,gamma=0.01)
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
#print(list(Y_pred))

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

Y_pred_new=svc_model.predict(X_train)
print(confusion_matrix(Y_train,Y_pred_new))
print(classification_report(Y_train,Y_pred_new))

[[ 85  18]
 [  7 132]]
              precision    recall  f1-score   support

         0.0       0.92      0.83      0.87       103
         1.0       0.88      0.95      0.91       139

    accuracy                           0.90       242
   macro avg       0.90      0.89      0.89       242
weighted avg       0.90      0.90      0.90       242



In [71]:
acc=accuracy_score(Y_test, Y_pred_log)
acc

0.7704918032786885